### PR TITLE
VSS-28 Initialize React project and add dependencies

### PR DESCRIPTION
**Pull request by augustinapetrr**
[VSS-28](https://maplesyrupbuns.atlassian.net/browse/VSS-28) In this PR a new React repository was initialized and `bootstrap` and `react-query` dependencies were added.

### CODE REVIEW

**Review by ago-ble — COMMENTED** [review]
Looks okey for me. Haven't tested it though.

**Review by kristupas-g — CHANGES_REQUESTED** [review]
The webapp project should be initialized in the project root and we dont need another .gitignore instead extend the existing one

**Review by kristupas-g — CHANGES_REQUESTED** [review]
You added the `node_modules` folder to the repository. This is not needed because we can pull the dependencies when we build locally. :)

**Comment by aauga** [comment]
covered by https://github.com/kristupas-g/videoteka-app/pull/5

**Pull request closed without merging**
